In [1]:
import pandas as pd
import numpy as np

In [32]:
df = pd.read_csv('Data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [12]:
df.info

<bound method DataFrame.info of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [33]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [14]:
df.isnull().sum()# null value in dataset

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

Fill Null value wiht mean values of Age and Salary

In [34]:
df[['Age', 'Salary']] = df[['Age', 'Salary']].fillna(df[['Age', 'Salary']].mean())
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [35]:
# Encoding. find varibale categories
df_unique = df.nunique()
df_unique

Country       3
Age          10
Salary       10
Purchased     2
dtype: int64

In [36]:
df_unique = df.nunique().to_frame().reset_index()
df_unique.columns = ['Varialbe','count']
df_unique

Varialbe  count
0    Country      3
1        Age     10
2     Salary     10
3  Purchased      2

we can ecode the varibale country and Purchased. We can use Label ecoding for 'Purchased' and ohe hot encoding for 'Country'.

In [37]:
# with map function
df['Purchased'] = df['Purchased'].map({'Yes':True, 'No': False})
df

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000      False
1    Spain  27.000000  48000.000000       True
2  Germany  30.000000  54000.000000      False
3    Spain  38.000000  61000.000000      False
4  Germany  40.000000  63777.777778       True
5   France  35.000000  58000.000000       True
6    Spain  38.777778  52000.000000      False
7   France  48.000000  79000.000000       True
8  Germany  50.000000  83000.000000      False
9   France  37.000000  67000.000000       True

In [38]:
# with label encoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

df['Purchased']= label_encoder.fit_transform(df['Purchased'])
df

Country        Age        Salary  Purchased
0   France  44.000000  72000.000000          0
1    Spain  27.000000  48000.000000          1
2  Germany  30.000000  54000.000000          0
3    Spain  38.000000  61000.000000          0
4  Germany  40.000000  63777.777778          1
5   France  35.000000  58000.000000          1
6    Spain  38.777778  52000.000000          0
7   France  48.000000  79000.000000          1
8  Germany  50.000000  83000.000000          0
9   France  37.000000  67000.000000          1

Creating a dummy variable


In [44]:
lst = []
for i in df.keys():
    lst.append(i)
print(lst)

['Age', 'Salary', 'Purchased', 'Country_France', 'Country_Germany', 'Country_Spain']


In [45]:
b = []
for i in df.keys():
  b.append(i)
print(b)

['Age', 'Salary', 'Purchased', 'Country_France', 'Country_Germany', 'Country_Spain']


In [46]:
df

Age        Salary  Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000          0               1                0   
1  27.000000  48000.000000          1               0                0   
2  30.000000  54000.000000          0               0                1   
3  38.000000  61000.000000          0               0                0   
4  40.000000  63777.777778          1               0                1   
5  35.000000  58000.000000          1               1                0   
6  38.777778  52000.000000          0               0                0   
7  48.000000  79000.000000          1               1                0   
8  50.000000  83000.000000          0               0                1   
9  37.000000  67000.000000          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

In [48]:
b.remove('Purchased')

In [49]:
b

['Age', 'Salary', 'Country_France', 'Country_Germany', 'Country_Spain']

In [51]:
X = df[b].values#array of features
y = df['Purchased'].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

Feature Scaling

In [52]:
from sklearn.preprocessing import StandardScaler ## standrard scalig 
scaler = StandardScaler() #initialise to a variable
scaler.fit(X_train,y_train) # we are finding the values of mean and sd from the td
X_train_scaled = scaler.transform(X_train) # fit (mean, sd) and then transform the training data
X_test_scaled = scaler.transform(X_test) # transform the test data

In [53]:
print(X_train_scaled)

[[ 0.26306757  0.12381479 -1.          2.64575131 -0.77459667]
 [-0.25350148  0.46175632  1.         -0.37796447 -0.77459667]
 [-1.97539832 -1.53093341 -1.         -0.37796447  1.29099445]
 [ 0.05261351 -1.11141978 -1.         -0.37796447  1.29099445]
 [ 1.64058505  1.7202972   1.         -0.37796447 -0.77459667]
 [-0.0813118  -0.16751412 -1.         -0.37796447  1.29099445]
 [ 0.95182631  0.98614835  1.         -0.37796447 -0.77459667]
 [-0.59788085 -0.48214934  1.         -0.37796447 -0.77459667]]


In [54]:
print(X_test_scaled)

[[-1.45882927 -0.90166297 -1.          2.64575131 -0.77459667]
 [ 1.98496442  2.13981082 -1.          2.64575131 -0.77459667]]
